name: Compliance and Integrity

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  validate:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verify credits block in README
        shell: pwsh
        run: |
          $readme = Get-Content README.md -Raw
          $required = @(
            "Creators and Permanent Credits",
            "Perplexity.labs",
            "Jacob Scott Farmer",
            "mistral (production integration)"
          )
          foreach ($r in $required) {
            if ($readme -notmatch [Regex]::Escape($r)) {
              Write-Error "Missing credit token: $r"
            }
          }

      - name: Hash configs and compare integrity.json
        shell: pwsh
        run: |
          $manifest = Get-Content "configs/integrity.json" -Raw | ConvertFrom-Json
          $errors = 0
          foreach ($c in $manifest.configs) {
            $path = Join-Path "configs" $c.name
            if (-not (Test-Path $path)) { Write-Error "Missing config $($c.name)"; $errors++ ; continue }
            $hash = (Get-FileHash -Algorithm SHA256 -Path $path).Hash.ToLower()
            if ($c.sha256 -and $c.sha256.ToLower() -ne $hash) {
              Write-Error "Hash mismatch for $($c.name): $($c.sha256) != $hash"
              $errors++
            }
          }
          if ($errors -gt 0) { exit 1 }
          Write-Host "Integrity OK"
