name: Safe ML Asset Pipeline
on:
  push:
    branches: [main]
  schedule:
    - cron: '0 0 * * 0' # Weekly sanitization

jobs:
  security-scan:
    runs-on: ubuntu-latest
    container:
      image: pytorch/pytorch:latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python with safety checks
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        check-latest: true

    - name: Install dependencies with vulnerability scanning
      run: |
        python -m pip install --upgrade pip
        pip install safety numpy torch
        safety check -r requirements.txt || exit 1

    - name: Validate ML libraries
      run: |
        python -c "import torch; print(f'PyTorch version: {torch.__version__}')"
        python -c "import numpy; print(f'NumPy version: {numpy.__version__}')"
        # Verify no unsafe operations
        python scripts/validate_ml_operations.py

    - name: Sanitize ML models
      run: |
        python scripts/sanitize_models.py --libraries pytorch numpy
        # Checks for:
        # 1. Unsafe tensor operations
        # 2. Numerical stability issues
        # 3. Ethical compliance flags

    - name: Run ALN Batch Generator
      env:
        ML_SAFETY_MODE: "strict"
      run: |
        aln run generate_assets --safe-mode \
          --input registry/assets.yml \
          --output data/ledger/placements.ndjson \
          --seed "session:${GITHUB_RUN_ID}"

    - name: Ethical compliance check
      run: |
        python scripts/ethical_compliance.py --check \
          --input data/ledger/placements.ndjson \
          --output reports/compliance.json

    - name: Commit sanitized assets
      if: success()
      run: |
        git config user.name "safe-ml-bot"
        git config user.email "safe-ml@github.com"
        git add .
        git commit -m "Weekly ML sanitization [skip ci]" || true
        git push

  wasm-validation:
    needs: security-scan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: wasmerio/wapm-cli-action@v1
      with:
        cmd: validate approvals/*.wasm --ethics-check
