
name: Silent Perimeter CI
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: python ops/devops/snowflake_sync.py
      - run: godot --path world/maps/silent-perimeter --export
      - run: |
          git config --global user.name "Wolfman AI"
          git add .
          git commit -m "Auto-sync configs [Wolfman Approved]"
          git push
